#cloud-config
local-hostname: ${guest_hostname}
network:
  version: 2
  ethernets:
    ens160:
      dhcp4: false
      dhcp6: false
      addresses:
        - ${ipv4_address}${ipv4_cidr}
      gateway4: ${ipv4_gateway} 
      routes:
        - to: 0.0.0.0/0
          via: ${ipv4_gateway}
      nameservers:
        search: [${dns_search_domain_1}]
        addresses:
        - ${ipv4_dns_server_1}
        - ${ipv4_dns_server_2}

wait-on-network:
  ipv4: true